env: "local"

database:
  db_host: "${DB_HOST}"
  db_port: "${DB_PORT}"
  user: "${DB_USER}"
  pass: "${DB_PASS}"
  name: "${DB_NAME}"

server:
  port: "${SERVER_PORT}"
  host: "${SERVER_HOST}"

jwt:
  secret: "${JWT_SECRET}"
  token_lifespan: "${JWT_TOKEN_LIFESPAN}"

email:
  smtp_HOST: "${SMTP_HOST}"
  smtp_PORT: "${SMTP_PORT}"
  username: "${SMTP_USER}"
  password: "${SMTP_PASS}"

aws:
  bucket: "${BUCKET}"

blockchain:
  rpc_url: "${RPC_URL}"
  memcoin_addr: "${MEMCOINADDR}"
  memcoin_factory_addr: "${MEMCOIN_FACTORY_ADDR}"
  private_key: "${PRIVATE_KEY}"