CREATE TABLE songs (
    ID BIGSERIAL PRIMARY KEY,
    NameSong VARCHAR(255) NOT NULL,
    Artist VARCHAR(255) NOT NULL,
    AlbumID BIGINT REFERENCES albums(ID) ON DELETE CASCADE,
    Image VARCHAR(255) NOT NULL
);

CREATE INDEX name_songs_idx ON songs (NameSong);